region              = "ap-south-1"
vpc_cidr           = "10.0.0.0/16"
public_subnets     = ["10.0.1.0/24", "10.0.2.0/24"]
availability_zones = ["ap-south-1a", "ap-south-1b"]
bucket_name     = "sb3bucket33"
acl                           = "log-delivery-write"
force_destroy                 = true
object_ownership              = "ObjectWriter"
attach_elb_log_delivery_policy = true
attach_lb_log_delivery_policy  = true
attach_waf_log_delivery_policy = false
versioning_enabled            = true
